[theme]
# General colors
primaryColor = "#00FF00"             # Accent color (matches your green buttons)
backgroundColor = "#121212"          # Main background (matches .main)
secondaryBackgroundColor = "#1E1E1E" # Sidebar, inputs, sliders, etc.
textColor = "#FFFFFF"                 # Default text color
font = "sans serif"                   # Font type

[server]
headless = false
enableCORS = false